name: Main
on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker And Run Container With SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/dingtalk/dingtalk-springboot/
            git pull origin master
            mvn package -DskipTests
            cd ~/dingtalk
            docker-compose build
            docker-compose up -d
            docker image prune -f
